-- MySQL Script generated by MySQL Workbench
-- Sat Jun 19 16:44:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema arm_engiens
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `arm_engiens` ;

-- -----------------------------------------------------
-- Schema arm_engiens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arm_engiens` DEFAULT CHARACTER SET utf8 ;
USE `arm_engiens` ;

-- -----------------------------------------------------
-- Table `arm_engiens`.`engines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arm_engiens`.`engines` ;

CREATE TABLE IF NOT EXISTS `arm_engiens`.`engines` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `value` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `value`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
